#!docker-compose.yml

nginx-ssl-proxy:
  image: gtsconsulting/nginx-ssl-proxy
  restart: always
  environment:
    SERVERNAME: gtsconsulting.ma
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - "/etc/letsencrypt"
